# Generated by Django 6.0 on 2026-01-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_birth_date_user_is_email_verified_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
